### ISSUE TITLE
import folding does not handle line continuations

### ISSUE THREAD

**Issue by anntzer** [tmhedberg/SimpylFold#61] opened 2016-05-09 05:35 UTC
Both
```
from foo import bar, \
    baz
from quux import quux
```
and
```
from foo import (bar,
                 baz)
from quux import quux
```
confuse the import folder (#56).

**Comment by tmhedberg** [comment] 2016-05-09 20:38
This is a dupe of #58.

**Closed by tmhedberg** 2016-05-09 20:38 UTC
