### ISSUE TITLE
Fold lists

### ISSUE THREAD

**Issue by SicariusNoctis** [tmhedberg/SimpylFold#95] opened 2017-11-22 05:01 UTC
It would be nice to fold long lists (and dictionaries):

```
dotfiles = [
    '~/.aliases',
    '~/.xinitrc',
    '~/.Xmodmap',
    '~/.vimrc',
    '~/.zshrc',
]
```

**Comment by nfnty** [comment] 2017-11-22 07:19
Duplicate of #67.

**Closed by nfnty** 2017-11-22 07:19 UTC
Labels: duplicate, enhancement
